[workspace]
channels = [
  "https://srgconda.bj.bcebos.com",
  "https://prefix.dev/meta-forge",
  "conda-forge",
]
name = "etha"
platforms = ["linux-64"]
version = "0.1.0"

[tasks.submit]
cmd = "kjobctl create slurm --first-node-ip -- --chdir $PIXI_PROJECT_ROOT --output $PIXI_PROJECT_ROOT/jobs-%j-%N.out --error $PIXI_PROJECT_ROOT/jobs-%j-%N.err {{ script }}"
args = ["script"]

[system-requirements]
cuda = "12.9"

[dependencies]
nccl = "2.19.3.*"
nccl-tests = ">=2.17.6,<3"
perl-test = ">=1.26,<2"
